version: "3.7"
services:
  review-scraper:
    build:
      context: .
    image: review-scraper
    volumes:
      - "/usr/local/bundle"
      - ".:/gem"
    networks:
      - default


networks:
  default:
    external:
      name: local-network
